### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Gabrielk99** [deworrall92/groupConvolutions#17]
Hey, i work in a project and i need implement a harmonic convolution to work with audio. but i cant understand very well how the layer work, and you implemented this layer, you have a some material that explains this ?

**Comment by danielewworrall** [comment]
Original paper is here: https://arxiv.org/abs/1612.04642 or a more recent paper with code: https://arxiv.org/abs/1911.08251. I'm not sure how rotational equivariance could be useful for audio, but good luck :)

**Comment by Gabrielk99** [comment]
I read a paper with harmonic convolution tô reduções noises in áudio data

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
