### ISSUE TITLE
Error trying to run demo

### ISSUE THREAD

**Issue by bigsnarfdude** [deworrall92/groupConvolutions#2]
```
python train.py 0 mnist deep_stable rotated_data
```

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'train_phase' with dtype bool
         [[Node: train_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Snippet Error found here:
https://gist.github.com/bigsnarfdude/a919f70e9afcf427935a26494800a5e8

**Comment by StephanGarbin** [comment]
Thanks for noting this! **The readme stated incorrectly that tf 0.12 was supported. This bug does not show up in 0.11 which is the version we are targeting**. Docs have been amended and support for 0.12 is on our list of todos and should be available in the next couple of weeks.
Also note: a host of other warnings show up relating to various API changes in 0.12.

**Comment by bigsnarfdude** [comment]
Resolved by setting up Tensorflow r.0.11 in virtualenv:

```
sudo apt-get install python-pip python-dev python-virtualenv
virtualenv --system-site-packages ~/tensorflow
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
sudo pip install --upgrade $TF_BINARY_URL
```
