### ISSUE TITLE
Understanding the code

### ISSUE THREAD

**Issue by siddharthm28** [deworrall92/groupConvolutions#9]
Hi,

I'm trying to understand how the filters are implemented in your code and how you are using them. Specifically, I'm not very clear on what's happening in the functions get_interpolation_weights and get_filters. Fig. 6 of the paper is clear and I'm guessing the above 2 functions are how you implement it ? Any help will be hugely appreciated. I know you have commented the functions (and the code in general) with a lot of detail but a high-level overview will be very helpful to future readers/users. Also, I see that you're using n_rings=4 with filter_size=5 in the MNIST-rot/run_mnist.py. To capture all weights of the 5x5 weight matrix (again Fig.6), you have 6 rings (including one of radius=0). What am I missing ?

Thanks again !
-Siddharth

**Comment by danielewworrall** [comment]
Hi Siddarth, I'll try and put together a nice README or something of that sort at the end of the week (currently abroad for the week). Hope that's okay. In the meantime:

[`get_filters`](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L276): We store all of the filters as a list of radial weightings `R` and phase offsets `P`. Specifically `R` is a list of tuples `[(m0, r0), (m1, r1),...]`, where `(mi, ri)` are the rotation order and radial weighting vector for a single complex filter. We iterate through `R` and for each element of `r`, which is a weight for a different ring, we need to represent the filter in a Cartesian basis (regular filters).

[`get_interpolation_weights`](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L250) returns a [3D array](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L285) (let's call it `interpolation_array`) of shape `[n_radii, n_angles, n_pixels]`, such that if we index into `interpolation_array[my_radius, my_angle, :]`, we have Gaussian smoothed interpolation weights in the pixel-basis for the polar position `(my_radius, my_angle)`.

To produce a filter of rotation order `m`, we take a single frequency complex sinusoid, which is the [`m`th row of a DFT matrix](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L286) and [project](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L287) that into the pixel basis using `interpolation array`. We then [split the complex filter into real and imaginary parts](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L289) (which I've called `cosine` and `sine`---probably a poor naming convention). After that, we make sure to [reweight each ring](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L296) using the corresponding element of `r`. If `P` is present we also [apply the phase shift](https://github.com/deworrall92/harmonicConvolutions/blob/9cb6e439499fb0a9355fa1068b1590fa1d813643/harmonic_network_ops.py#L299), which effectively rotates the filter.

Hope that helps :)

**Comment by danielewworrall** [comment]
Oh also, about the number of rings, we refactored the code after running the experiments, so it's most likely a mistake :S That said, for rotation orders other than 0, you do not need a ring for radius 0, because the filters can only assume a value of zero at the center pixel.
